apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-go
  labels:
    app: auth-go
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-go
  template:
    metadata:
      labels:
        app: auth-go
    spec:
      containers:
      - name: auth-go
        image: auth-go:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: auth-go-config
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
