version: "3.9"

services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=testuser
      - DB_PASSWORD=testpass
      - DB_NAME=test_db
      - DATABASE_URL=testuser:testpass@tcp(db:3306)/test_db?parseTime=true&loc=Local
    ports:
      - "8081:8080"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: test_db
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    ports:
      - "3316:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-ptestpass"]
      timeout: 5s
      retries: 10
      interval: 5s
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
