apiVersion: v1
kind: Service
metadata:
  name: {{ include "auth-go.fullname" . }}-api
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: {{ include "auth-go.name" . }}-api
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "auth-go.fullname" . }}-mysql
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: {{ include "auth-go.name" . }}-mysql
